version: '3'
services:
  database:
    container_name: agreena_postgres_db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: agreena
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/postgres_data
    networks:
      - agreena-local-dev-network
    ports:
      - "7893:5432"
networks:
  agreena-local-dev-network:
    external: true
